With numpy you can create multidimensional arrays that are all of the same type. the underlaying implementation is in C so manipulating the arrays are as efficient as possible

In [1]:
import numpy as np
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [2]:
a = a.reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
a.dtype.name

'int64'

In [6]:
a.itemsize

8

In [7]:
a.size

15

## Array Creation

In [8]:
b = np.array(['o', 'tuuuuuuuuuuuuu', 't444444rrrrrrrrrrrrrrrr44444444444', 'f']).reshape(2, 2)
b

array([['o', 'tuuuuuuuuuuuuu'],
       ['t444444rrrrrrrrrrrrrrrr44444444444', 'f']], dtype='<U34')

In [9]:
print(b.itemsize, '\n')
print(b.dtype)

136 

<U34


.itemsize seems to be equal to the size of the largest item in the array, <U34 seems to mean that the larges string is 34 chracters long

In [10]:
c = np.array([(2.1, 4, 3), (7, 2, 1)])
print(c, '\n')
print(c.dtype)

[[2.1 4.  3. ]
 [7.  2.  1. ]] 

float64


In [11]:
d = np.array([((1, 2), (3, 4)), ((5, 6), (7, '8'))])
print(d, '\n')
print(d.dtype)

[[['1' '2']
  ['3' '4']]

 [['5' '6']
  ['7' '8']]] 

<U21


You can pass an array of tuples into the array method to create a multidimensional array
if intergers and floats are combined the ints will be cast into floats
if strings are mixedin anywhere then they will all be cast into strings

In [12]:
e = np.zeros( (2,3,5) )
print(e)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [13]:
f = np.ones( (2,3,5) )
print(f, '\n')
print(f.dtype)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]] 

float64


you can initialize an array of a known size so you don't have to spend all the time and resources to modify the size of another, defaults to type float

In [14]:
g = np.arange(10, 30, 5)
print(g)

[10 15 20 25]


In [15]:
h = np.arange(10, 30, 6.2)
print(h)

[10.  16.2 22.4 28.6]


In [16]:
i = np.linspace(10, 30, 5)
print(i)

[10. 15. 20. 25. 30.]


You can use .arange to generate an array @start(inculive) to @end(exclusive) with @step

you can also use .linspace to generate an array of @start(inclusive) to @end(inclusive) divided by @n elements

you can't really predict the actual number of elements obtained using .arange() when using floats(because of floating point precision) so it's possible that you will be one off if you use it for generating an array of a specific length. it would be more appropriate to use .linspace() in that scenerio

In [17]:
j = np.array([10, 20, 30, 40])
k = np.arange()

TypeError: arange() missing required argument 'start' (pos 1)